export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';

export const GET_GOAL_REQUEST = 'GET_GOAL_REQUEST';
export const GET_GOAL_RESPONSE = 'GET_GOAL_RESPONSE';

export const UPDATE_GOAL_REQUEST = 'UPDATE_GOAL_REQUEST';
export const UPDATE_GOAL_RESPONSE = 'UPDATE_GOAL_RESPONSE';

export const ADD_GOAL_REQUEST = 'ADD_GOAL_REQUEST';
export const ADD_GOAL_RESPONSE = 'ADD_GOAL_RESPONSE';
