export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';

export const GET_GOAL_REQUEST = 'GET_GOAL_REQUEST';
export const GET_GOAL_RESPONSE = 'GET_GOAL_RESPONSE';

export const UPDATE_GOAL_REQUEST = 'UPDATE_GOAL_REQUEST';
export const UPDATE_GOAL_RESPONSE = 'UPDATE_GOAL_RESPONSE';

export const ADD_GOAL_REQUEST = 'ADD_GOAL_REQUEST';
export const ADD_GOAL_RESPONSE = 'ADD_GOAL_RESPONSE';

export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST';
export const UPDATE_TASK_RESPONSE = 'UPDATE_TASK_RESPONSE';

export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const ADD_TASK_RESPONSE = 'ADD_TASK_RESPONSE';

export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST';
export const DELETE_TASK_RESPONSE = 'DELETE_TASK_RESPONSE';

export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
export const ADD_TODO_RESPONSE = 'ADD_TODO_RESPONSE'

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'
export const DELETE_TODO_RESPONSE = 'DELETE_TODO_RESPONSE'

export const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST'
export const UPDATE_TODO_RESPONSE = 'UPDATE_TODO_RESPONSE'
